apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lbthu0b17-go
  janus-idp.io/tekton: lbthu0b17-go
  backstage.io/kubernetes-id: lbthu0b17-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lbthu0b17-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
